### PR TITLE
docs: Update misc. broken links

### PR DESCRIPTION
**Pull request by tanmay-pnaik**

### CODE REVIEW

**Comment by tanmay-pnaik** [comment]
Oops, just saw https://github.com/bank-vaults/bank-vaults.dev/pull/118

**Comment by tanmay-pnaik** [comment]
> Oops, just saw #118

IMHO, we can merge these for the time being, and then work on the larger improvements of https://github.com/bank-vaults/bank-vaults.dev/pull/118. The broken links on our _primary_ documentation reduce the developers' trust in the product.

**Review by sagikazarmark — APPROVED** [review]

**Comment by sagikazarmark** [comment]
Makes sense, thanks!

**Comment by tanmay-pnaik** [comment]
Fixes https://github.com/bank-vaults/bank-vaults.dev/issues/117

**Pull request merged**
